#
# Multi-user application for luci
# Added new functions for compatibility for 18.06.1 
# Hostle 2/7/2019 hostle19@gmail.com
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Multi User Support
LUCI_DEPENDS:=+luci-mod-admin-full +libuci-lua

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
